admin:
  username: myfavoritename
  password_hash: be121740bf988b2225a313fa1f107ca1
  secret: a secret something
  deployCommand: hexo deploy
options:
  lineNumbers: true
  spellcheck: true
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
